apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-creator-job
  namespace: flyte
spec:
  template:
    spec:
      containers:
      - name: bucket-creator
        image: minio/mc
        command: ["/bin/sh"]
        args:
          - -c
          - mc alias set minio http://minio:9000 minio miniostorage --api S3v4 && mc mb minio/my-s3-bucket && mc mb minio/mlflow
      restartPolicy: Never
